FROM python:3.11-slim

# Set the working directory
WORKDIR /src

# Install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Run the main Python script
# CMD ["python", "dags/kaggle_dag.py"]
