FROM python:3.11-slim

# Set the working directory
WORKDIR /src

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set Kaggle environment variable and config directory
ENV KAGGLE_CONFIG_DIR=/root/.kaggle

# Copy kaggle.json to the correct location
RUN mkdir -p /root/.kaggle
COPY kaggle.json /root/.kaggle/kaggle.json
RUN chmod 600 /root/.kaggle/kaggle.json

# Copy all project files
COPY . .

# Run the main Python script
CMD ["python", "app/main.py"]


