# Use an official Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /src

# Copy all project files to the container
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Run the main script
CMD ["python", "app/main.py"]
